version: '3.8'

networks:
  prosiga_net:
    external: true

services:
  auth-api:
    build: .
    container_name: auth-prosiga
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    networks:
      - prosiga_net
    environment:
      - DB_CONNECT_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-prosiga:5432/${POSTGRES_DB}